CREATE TABLE steam_gamelist (
  app_id INTEGER NOT NULL PRIMARY KEY,
  game_title VARCHAR(255) NOT NULL,
  time_stamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) engine=InnoDB;